import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Leftnav from '../app/Leftnav/page';
import Header from '../app/Header/page';
import { Box } from '@mui/material';
import { KeywordProvider } from '../app/Component/page'; // <-- ✅ IMPORT THE PROVIDER

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Intelli',
  description: 'Generated by create next app',
};

const RootLayout: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  return (
    <html lang="en">
      <body className={inter.className}>
        <KeywordProvider> {/* ✅ Wrap your entire layout */}
          <Box display="flex">
            <Leftnav />
            <Box flexGrow={1}>
              <Header />
              <main>{children}</main>
            </Box>
          </Box>
        </KeywordProvider>
      </body>
    </html>
  );
};

export default RootLayout;
