import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Leftnav from '../app/Leftnav/page';
import Header from '../app/Header/page';
import { Box } from '@mui/material';


const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Intelli',
  description: 'Generated by create next app',
};

const RootLayout: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  return (
    <html lang="en">
      <body className={inter.className}>
      
    
      <Box display="flex">
      <Leftnav />
      <Box flexGrow={1}>
        <Header />
       

        <main>{children}</main>
        </Box>
        </Box>
      </body>
     
    </html>
  );
};

export default RootLayout;
